### ISSUE TITLE
libgcc_s_seh-1.dll is missing

### ISSUE THREAD

**Issue by DCxDemo** [Danixu/ecm-tools-reloaded#9]
Hey, it's nice to see the good old ECM tool reincarnation.

It looks like current release EXE asks for libgcc_s_seh-1.dll and it probably shouldn't, here's SO question on topic.

https://stackoverflow.com/questions/18138635/mingw-exe-requires-a-few-gcc-dlls-regardless-of-the-code

**Comment by Danixu** [comment]
Hello,

Yeah, I always loved this format because helps to save a lot of space on CD-ROM collections, but I wanted to make it better making it seekable. The original format was using a block kind that made it non seekable or at least very hard to index. If I get it, will help to save some space on portable consoles SD cards.

Thanks for the report. I was testing it on my computer which has MinGW installed, so I have not detected that Issue. I'll take a look and I'll fix it.

Best regards.

**Comment by Danixu** [comment]
Hi,

I have reuploaded the latest version with the fixed flag, so will no need the library anymore. I'll leave open this issue to check and reupload the older versions.

Thanks again for the report.

Best regards.
